### ISSUE TITLE
Unable to build the solution

### ISSUE THREAD

**Issue by Lark3D** [DjvuNet/DjvuNet#84]
Hello!
I see that just two days ago you implemented .net standard 2.0 support, congrats on that!
I'm trying to implement some djvu reading functionality in my UWP app, and i want to use this library. 
However, i wasn't able to build the solution neither following the tips in readme with a command line, nor with VS2017. I get a lot of different errors, and some of them seem like there are some libraries missing in my system.
Can you please tell me if the current version works and the problem is on my side?
Also, which tools, frameworks, libraries do one need in order to build the solution or specifically .net core/.net standard projects?
Thank you!

**Comment by 4creators** [comment]
Sorry for late reaction I have just returned from my vacations.

To build for .Net Standard 2.0 it is necessary to use at least VS 2017 v15.3 Preview 2. VS 2017 Preview currently is in [Preview 4](https://www.visualstudio.com/thank-you-downloading-visual-studio/?ch=pre&sku=Community&rel=15) release. The link directs to VS 2017 15.3 Community edition download. VS 2017 RTM release which has version 15.2 will not work since there is no support for .NET Core 2.0 SDK yet. I suspect it will come in RTM releases not earlier than with final release of Core .NET 2.0 RTM what is expected in fall this year. If you want to use library for UWP app it will work only with UWP 6.0 which will be released together with Windows 10 Fall Creators Update. Until then due to multiple missing APIs in netstandard1.4 which is the latest API set supported by UWP DjvuNet will not work. However, it will work on preview versions of .NET Core 2.0 SDK.

Build instructions in README are currently out of date and I have to put there all necessary info on build system changes and required build steps to enable hassle free build experience for everyone. 

Build on .NET Framework v4.6.1 works out of the box for VS 2017 RTM if one follows AppVeyor continous integration script instructions which are located in [.appveyor.yml](https://github.com/DjvuNet/DjvuNet/blob/master/.appveyor.yml) file. To build for netstandard2.0 target first build for .NET Framework to restore all dependencies. Build depends on two other libraries which have to be cloned into subdirectories according to git clone instructions from .appveyor.yml

I will update both BUILD.cmd and README to reflect all this changes very soon.

**Comment by 4creators** [comment]
Current README build description reflects what is working for netstandard2.0 and necoreapp2.0 targets. Please test .NET Core 2.0 build instructions and give feedback in case of any problems.

**Comment by Lark3D** [comment]
Thank you very much for your response, i will test it soon!
